apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-crawler
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: where-for-dinner-crawler
    networking.knative.dev/visibility: cluster-local    
spec:
  env:
  - name: spring_profiles_active
    value: rabbitmq
  - name: SPRING_CONFIG_IMPORT
    value: "optional:configtree:${SERVICE_BINDING_ROOT}/config/"   
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http      
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"      
  serviceClaims:
  - name: config
    ref:
      apiVersion: config.apps.tanzu.vmware.com/v1alpha4
      kind: ConfigurationSlice
      name: where-for-dinner-cralwer-config-slice       
  source:
    git:
      url: https://github.com/gm2552/where2_acsdemo
      ref:
        branch: main
    subPath: where-for-dinner-crawler